// <auto-generated />
using System;
using Infrastructure.Configuration;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20241119202724_GlobalSolutionBancoDotnet")]
    partial class GlobalSolutionBancoDotnet
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.ContasEnergia", b =>
                {
                    b.Property<int>("id_conta_energia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_conta_energia"));

                    b.Property<DateTime>("Data")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("data");

                    b.Property<double>("Quantidadekwh")
                        .HasColumnType("BINARY_DOUBLE")
                        .HasColumnName("quantidade_kwh");

                    b.Property<double>("Valoreconomizado")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<double>("Valorgastoreal")
                        .HasColumnType("BINARY_DOUBLE")
                        .HasColumnName("valor_gasto_real");

                    b.Property<double>("Valortotalecologico")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<int>("id_preco_ecologico")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("id_usuario")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("id_conta_energia");

                    b.ToTable("DotnetGS_Contas_Energia");
                });

            modelBuilder.Entity("Domain.Entities.PrecoEcologico", b =>
                {
                    b.Property<int>("id_preco_ecologico")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_preco_ecologico"));

                    b.Property<DateTime>("Data")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("data");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("estado");

                    b.Property<double>("Valor1kwh")
                        .HasColumnType("BINARY_DOUBLE")
                        .HasColumnName("valor_1kwh");

                    b.HasKey("id_preco_ecologico");

                    b.ToTable("DotnetGS_Preco_Ecologico");
                });

            modelBuilder.Entity("Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("id_usuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_usuario"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("estado");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("login");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("nome");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("senha");

                    b.HasKey("id_usuario");

                    b.ToTable("DotnetGS_Usuario");
                });
#pragma warning restore 612, 618
        }
    }
}
